version: '3.8'

services:
  backend:
    build:
      context: ./backend        
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/recruitment_task/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always